Friend v1 milestone
AhmedAmin90/ror-social-scaffold pull request #3
Opened 2021-02-24 21:34 UTC by AhmedAmin90

In this milestone: 
- We created a friendship relationship between users with these features:
1. Send friend requests.
2. Accept new friend request.
3. Reject a friend request.
- We created a friend list and a pending list of friend requests on the user single page.
- We made tests for user and friend models and features.

2021-02-25 01:07 UTC, rindrajosia requested changes
Hello Team :wave:
Status: Changes Required :recycle:

Good job :+1:  your project looks nice, it works, no linter issue :smile:   but before approving this project let's cover a few details together to make your project better :blush: :arrow_double_down: . 

REQUIRED:

- [x] User model `has_many :inverted_friendships`, `class_name: "Friendship", foreign_key: "friend_id"` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/friend.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/)). I know that project works but, as the aim of this project is to learn more about association please, make this change.
- [x] Posts timeline includes posts written by logged-in user and their friends ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/friends_timeline.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/)). The only problem in your app is that, I can see someone else's post even if he is not my friend.
- [ ] Please remove any related logic from your views by using `helpers`
- [x] Remove all comments in your code.
- [x] Add test for Post model.

That's it, you can submit another code review request after making these changes
With all my respect :pray:

Rindra Josia

2021-02-26 09:03 UTC, peterrobert requested changes
### CHANGES REQUIRED ♻️ 

Hello @AhmedAmin90, very nice work making the changes as requested by the previous reviewer. 👏🏿  However, there are some more changes to be made kindly check below. ⬇️ 

- [ ] Kindly remember, you should always capitalize your first letter when making commits. This will help make your project more professional. Kindly from now on remember this because it's very important.

- Kindly check below ⬇️  for the requested change.

### if you have any question, kindly reach me via slack @peterrobert

### HAPPY CODING 💻

2021-02-26 09:03 UTC, peterrobert commented on app/views/users/_form.html.erb
> +<% end %>
- [x] Please remove logic from views. This is important because it helps your application follow the MVC pattern well. You can do this by using helpers to add all your logic.

Kindly read this [Article](http://codefol.io/posts/Where-Do-I-Put-My-Code/) to learn more about this.

<img width="825" alt="no_logic_in_helpers_requirement" src="https://user-images.githubusercontent.com/32361963/109278560-b58f6d00-7829-11eb-950a-2dab5419c6f7.png">

**NB:**

This applies to all other sections of your application. Kindly make sure there is no logic in your views then submit your project for another review.

2021-02-27 08:33 UTC, Temmarie approved these changes
## Status: Approved :heavy_check_mark:

### Hi @AhmedAmin90 and @rindrajosia ! :wave:

#### Thank you for making all of the required changes, your project is approved :clap: :clap: :clap: :tada:

#### You may merge, good luck with your next projects! :rocket:
#### Happy Coding! :+1:
__Grace Tamara Ekunola __
[GitHub](https://github.com/temmarie) | [LinkedIn](https://www.linkedin.com/in/ekunola-grace/) | [Twitter](https://twitter.com/TemmarieW)

2021-02-27 14:13 UTC, merged

2021-02-27 17:42 UTC, oloomoses reviewed
Congratulation!